### ISSUE TITLE
C# version still available?

### ISSUE THREAD

**Issue by thomasgalliker** [AlphaDelta/Merry-Chrimbus#1]
Awesome! This is a really nice xmas present for nerds :-) I like it! I wondee if you still have the C# version of it?

**Comment by AlphaDelta** [comment]
Hey dude, sorry about the slow reply.

Here's the C# version: https://pastebin.com/kkALZ07G

Be aware, there's a *lot* of pinvoke and messy code. I wrote the entire thing in the span of an ADHD-fueled hour.

**Comment by thomasgalliker** [comment]
Thanks for sharing. Have a good xmas/new year!
